<?php

$questions = [
  ['QuestionNo' => 1, 'QuestionText' => 'Jika pernah memiliki reksa dana, apakah jenisnya?'],
  ['QuestionNo' => 2, 'QuestionText' => 'Bagaimana pemahaman anda mengenai perkembangan investasi anda di reksa dana yang anda miliki dan industri reksa dana secara umum?'],
  ['QuestionNo' => 3, 'QuestionText' => 'Seberapa besar resiko yang anda dapat terima dalam investasi reksa dana?'],
  ['QuestionNo' => 4, 'QuestionText' => 'Bagaimana anda mengindikasikan diri anda dalam hal berinvestasi?'],
  ['QuestionNo' => 5, 'QuestionText' => 'Berapa banyak uang yang mampu anda tabung/sisihkan setiap bulannya dari pendapatan bulanan?'],
  ['QuestionNo' => 6, 'QuestionText' => 'Berapa persen dana yang anda investasikan pada jenis profuk reksa dana dari total aset yang anda miliki?'],
  ['QuestionNo' => 7, 'QuestionText' => 'Dimana anda menempatkan sebagian besar uang anda?'],
];

$questions_opt = [
  ['QuestionNo' => 1, 'OptionNo' => 1, 'OptionText' => 'Reksa dana pasar uang', 'OptionValue' => '10'],
  ['QuestionNo' => 1, 'OptionNo' => 2, 'OptionText' => 'Reksa dana Pendapatan Tetap', 'OptionValue' => '20'],
  ['QuestionNo' => 1, 'OptionNo' => 3, 'OptionText' => 'Reksa dana campuran', 'OptionValue' => '30'],
  ['QuestionNo' => 1, 'OptionNo' => 4, 'OptionText' => 'Reksa dana saham', 'OptionValue' => '40'],
  ['QuestionNo' => 2, 'OptionNo' => 1, 'OptionText' => 'Tidak tahu apa apa', 'OptionValue' => '10'],
  ['QuestionNo' => 2, 'OptionNo' => 2, 'OptionText' => 'Tahu sedikit', 'OptionValue' => '20'],
  ['QuestionNo' => 2, 'OptionNo' => 3, 'OptionText' => 'Memonitor dari waktu ke waktu', 'OptionValue' => '30'],
  ['QuestionNo' => 2, 'OptionNo' => 4, 'OptionText' => 'Memonitor dengan cermat', 'OptionValue' => '40'],
  ['QuestionNo' => 3, 'OptionNo' => 1, 'OptionText' => 'Keuntungan hingga 10%, kerugian hingga 5%', 'OptionValue' => '10'],
  ['QuestionNo' => 3, 'OptionNo' => 2, 'OptionText' => 'Keuntungan hingga 20%, kerugian hingga 10%', 'OptionValue' => '20'],
  ['QuestionNo' => 3, 'OptionNo' => 3, 'OptionText' => 'Keuntungan hingga 30%, kerugian hingga 20%', 'OptionValue' => '30'],
  ['QuestionNo' => 3, 'OptionNo' => 4, 'OptionText' => 'Kerugian hingga > 30%, kerugian hingga > 20%', 'OptionValue' => '40'],
  ['QuestionNo' => 4, 'OptionNo' => 1, 'OptionText' => 'Mengharapkan tidak ada risiko', 'OptionValue' => '10'],
  ['QuestionNo' => 4, 'OptionNo' => 2, 'OptionText' => 'Mengutamakan risiko yang kecil', 'OptionValue' => '20'],
  ['QuestionNo' => 4, 'OptionNo' => 3, 'OptionText' => 'Mencari cukup keuntungan dengan risiko kerugian moderat sesuai keuntungan', 'OptionValue' => '30'],
  ['QuestionNo' => 4, 'OptionNo' => 4, 'OptionText' => 'Mencari hasil yang besar dengan berani mengambil risiko kerugian yang besar', 'OptionValue' => '40'],
  ['QuestionNo' => 5, 'OptionNo' => 1, 'OptionText' => 'Hingga 10%', 'OptionValue' => '10'],
  ['QuestionNo' => 5, 'OptionNo' => 2, 'OptionText' => 'Antara 10% s.d 25%', 'OptionValue' => '20'],
  ['QuestionNo' => 5, 'OptionNo' => 3, 'OptionText' => 'Antara 25% s.d 50%', 'OptionValue' => '30'],
  ['QuestionNo' => 5, 'OptionNo' => 4, 'OptionText' => 'Lebih dari 50%', 'OptionValue' => '40'],
  ['QuestionNo' => 6, 'OptionNo' => 1, 'OptionText' => '< 10% dari total aset', 'OptionValue' => '10'],
  ['QuestionNo' => 6, 'OptionNo' => 2, 'OptionText' => '10% s.d 25% dari total aset', 'OptionValue' => '20'],
  ['QuestionNo' => 6, 'OptionNo' => 3, 'OptionText' => '25% s.d 50% dari total aset', 'OptionValue' => '30'],
  ['QuestionNo' => 6, 'OptionNo' => 4, 'OptionText' => '> 50% dari total aset', 'OptionValue' => '40'],
  ['QuestionNo' => 7, 'OptionNo' => 1, 'OptionText' => 'Tabungan & deposito', 'OptionValue' => '10'],
  ['QuestionNo' => 7, 'OptionNo' => 2, 'OptionText' => 'Mata uang asing', 'OptionValue' => '20'],
  ['QuestionNo' => 7, 'OptionNo' => 3, 'OptionText' => 'Reksa dana', 'OptionValue' => '30'],
  ['QuestionNo' => 7, 'OptionNo' => 4, 'OptionText' => 'Saham', 'OptionValue' => '40'],
];